apiVersion: v1
kind: Service
metadata:
  name: brain-tasks
spec:
  type: {{ .Values.service.type }}
  selector:
    app: brain-tasks
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort}}