version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: brain-tasks-app
    AWS_DEFAULT_REGION: us-east-1
    ACCOUNT_ID: 628590695807

phases:
  pre_build:
    commands:
      - echo Logging in to ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

      - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME

  build:
    commands:
      - echo Build started...
      - docker build -t $IMAGE_REPO_NAME .
      - docker tag $IMAGE_REPO_NAME:latest $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo Pushing image...
      - docker push $REPOSITORY_URI:latest